**DS 301: Applied Data Modeling and Predictive Analysis**

**Lab 3 - Logistic Regression**

# Logistic Regression with scikit-learn
Justin Park, September 2nd, 2022

We begin by importing the packages and modules that we will need.

In [44]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from common_plots import DigitPlotter

**Set up the data**

In [45]:
digits = load_digits()
print(digits.keys())
print("data shape: " + str(np.shape(digits.data)))
print("target shape: " + str(np.shape(digits.target)))
print("target_names: " + str(digits.target_names))
x = digits.data
y = digits.target

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])
data shape: (1797, 64)
target shape: (1797,)
target_names: [0 1 2 3 4 5 6 7 8 9]


**Split the data into training and test sets**

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print("Training set:\n" + str(np.c_[x_train, y_train]))
print("Testing set:\n" + str(np.c_[x_test, y_test]))

Training set:
[[ 0.  0.  0. ... 16.  6.  6.]
 [ 0.  3. 12. ...  2.  0.  5.]
 [ 0.  1. 10. ...  0.  0.  3.]
 ...
 [ 0.  0.  5. ...  0.  0.  7.]
 [ 0.  0.  4. ...  0.  0.  7.]
 [ 0.  0.  6. ...  0.  0.  8.]]
Testing set:
[[ 0.  0. 11. ... 16.  8.  2.]
 [ 0.  1. 15. ...  0.  0.  8.]
 [ 0.  2. 13. ... 16.  3.  2.]
 ...
 [ 0.  1.  9. ...  0.  0.  3.]
 [ 0.  0.  0. ...  2.  0.  8.]
 [ 0.  0.  0. ...  0.  0.  8.]]


**Train the model on the training set**

In [47]:
clf = LogisticRegression(max_iter = 10000).fit(x_train, y_train)

**Make predictions on the test set**

In [48]:
y_pred = clf.predict(x_test)
print(y_pred)

[2 8 2 6 6 7 1 9 8 5 2 8 6 6 6 6 1 0 5 8 8 7 8 4 7 5 4 9 2 9 4 7 6 8 9 4 3
 1 0 1 8 6 7 7 1 0 7 6 2 1 9 6 7 9 0 0 9 1 6 3 0 2 3 4 1 9 2 6 9 1 8 3 5 1
 2 8 2 2 9 7 2 3 6 0 9 3 7 5 1 2 8 9 3 1 4 7 4 8 5 8 5 5 2 5 9 0 7 1 4 7 3
 4 8 9 7 9 8 2 1 5 2 5 8 4 1 7 0 6 1 5 5 9 9 5 9 9 5 7 5 6 2 8 6 9 6 1 5 1
 5 9 9 1 5 3 6 1 8 9 8 7 6 7 6 5 6 0 8 8 9 8 6 1 0 4 1 6 3 8 6 7 4 9 6 3 0
 3 3 3 0 7 7 5 7 8 0 7 1 9 6 4 5 0 1 4 6 4 3 3 0 9 5 9 2 8 4 2 1 6 8 9 2 4
 9 3 7 6 2 3 3 1 6 9 3 6 3 3 2 0 7 6 1 1 9 7 2 7 8 5 5 7 5 2 3 7 2 7 5 5 7
 0 9 1 6 5 9 7 4 3 8 0 3 6 4 6 3 2 6 8 8 8 4 6 7 5 2 4 5 3 2 4 6 9 4 5 4 3
 4 6 2 9 0 6 7 2 0 9 6 0 4 2 0 7 9 8 5 4 8 2 8 4 3 7 2 6 9 9 5 1 0 8 2 8 9
 5 6 2 2 7 2 1 5 1 6 4 5 0 9 4 1 1 7 0 8 9 0 5 4 3 8 8]


**Compute the fraction of correctly classified samples in the test set**

In [49]:
print(metrics.accuracy_score(y_test, y_pred))
print(clf.score(x_test, y_test))

0.9583333333333334
0.9583333333333334
